### ISSUE TITLE
some problem for gcn

### ISSUE THREAD

**Issue by 302850047** [mbolleng2303/Master_Thesis#2]
Using backend: pytorch
cuda available with GPU: GeForce RTX 3090
[I] Loading dataset Task082_BraTS2020...
train, val sizes : 296 73
[I] Finished loading.
[I] Data load time: 0.1132s
MODEL DETAILS:

MODEL/Total parameters: GNet 15666
Training Graphs:  296
Validation Graphs:  73
Number of Classes:  1
Epoch 0:   0%|                                         | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/chenzhi/Chenjy/Master_Thesis-main/Train/train.py", line 29, in train_epoch_sparse
    batch_pos_enc = batch_graphs.ndata['pos_enc'].to(device)
  File "/data/chenzhi/.conda/envs/Chenjy/lib/python3.7/site-packages/dgl/view.py", line 66, in __getitem__
    return self._graph._get_n_repr(self._ntid, self._nodes)[key]
  File "/data/chenzhi/.conda/envs/Chenjy/lib/python3.7/site-packages/dgl/frame.py", line 393, in __getitem__
    return self._columns[name].data
KeyError: 'pos_enc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/chenzhi/Chenjy/Master_Thesis-main/main_u_net.py", line 404, in <module>
    main()
  File "/data/chenzhi/Chenjy/Master_Thesis-main/main_u_net.py", line 401, in main
    train_val_pipeline(MODEL_NAME, dataset, params, net_params, dirs)
  File "/data/chenzhi/Chenjy/Master_Thesis-main/main_u_net.py", line 162, in train_val_pipeline
    epoch)
  File "/data/chenzhi/Chenjy/Master_Thesis-main/Train/train.py", line 37, in train_epoch_sparse
    batch_scores = model.forward(batch_graphs, batch_x, batch_e)
  File "/data/chenzhi/Chenjy/Master_Thesis-main/Network/G_u_net.py", line 37, in forward
    hs = self.embed(a, hs)
  File "/data/chenzhi/Chenjy/Master_Thesis-main/Network/G_u_net.py", line 44, in embed
    h = self.embed_one(gs, hs)
  File "/data/chenzhi/Chenjy/Master_Thesis-main/Network/G_u_net.py", line 52, in embed_one
    h = self.s_gcn(g, h)
  File "/data/chenzhi/.conda/envs/Chenjy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/chenzhi/Chenjy/Master_Thesis-main/Layers/unet_graph_layer.py", line 59, in forward
    h = torch.matmul(g, h.float())
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument vec in method wrapper__mv)

Process finished with exit code 1

The dataset is Brats2020

**Comment by mbolleng2303** [comment]
Hi ! This is not the finished version of the code. You can contact me by email (maxime.bollengier@ulb.be) if you need some informations.
